### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by gltwy** [AdChain/AdChainRegistry#37]
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/Users/yinghai/.Trash/AdChainRegistry-master 17.08.27/node_modules/web3/lib/web3/errors.js:35:16)
    at XMLHttpRequest.request.onreadystatechange (/Users/yinghai/.Trash/AdChainRegistry-master 17.08.27/node_modules/web3/lib/web3/httpprovider.js:115:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/yinghai/.Trash/AdChainRegistry-master 17.08.27/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/yinghai/.Trash/AdChainRegistry-master 17.08.27/node_modules/xhr2/lib/xhr2.js:353:12)
    at XMLHttpRequest._onHttpRequestError (/Users/yinghai/.Trash/AdChainRegistry-master 17.08.27/node_modules/xhr2/lib/xhr2.js:542:12)
    at ClientRequest.<anonymous> (/Users/yinghai/.Trash/AdChainRegistry-master 17.08.27/node_modules/xhr2/lib/xhr2.js:413:24)
    at ClientRequest.emit (events.js:160:13)
    at TLSSocket.socketErrorListener (_http_client.js:389:9)
    at TLSSocket.emit (events.js:160:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! AdChainRegistry@0.0.1 compile: `truffle compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the AdChainRegistry@0.0.1 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by eccheung4** [comment]
Hi gitwy,
Thank you for reporting the error.  Off the top of my head, it could be the truffle version as this was developed very early on with an older truffle version.

However, please test using this repo instead.  The adChain Registry is using the forked version found here: https://github.com/skmgoldin/tcr
Sorry we will update README to point to that location.

**Comment by glthello** [comment]
@eccheung4  I followed the steps you gave me, but I made the same mistake as above.Why?

**Comment by eccheung4** [comment]
@gitwy you're having the same problem using tcr repo?
What truffle version are you using? Have testrpc running?
Thanks

**Comment by glthello** [comment]
@eccheung4
truffle --version
Truffle v4.0.6 - a development framework for Ethereum
npm --version
5.6.0

**Comment by eccheung4** [comment]
@gitwy 
you're using this repo?: https://github.com/skmgoldin/tcr 
what node version are you using?
node --version

**Comment by glthello** [comment]
@eccheung4 I used the repo,
 node --version
v9.5.0

**Comment by eccheung4** [comment]
@gitwy thanks for your patience!
I've matched your versions and seems ok for me.
Try npm rebuild
are you having problems when running npm run compile?

**Comment by glthello** [comment]
@eccheung4 Thanks! The problem has been solved

**Comment by eccheung4** [comment]
great @gitwy! Thanks for testing it out.
